#!/bin/bash

`dirname $0`/gitlogout

if [ "$3" == "" ]
then
  echo "sintaxe gitlogin user email name"
fi

ORIGIN=`git remote -v | grep origin.*fetch`
ORIGIN=${ORIGIN%(*)}
ORIGIN=${ORIGIN#origin*@}
ORIGIN=${ORIGIN#origin*://}
ORIGIN=`echo -n "${ORIGIN//[[:space:]]/}"`

echo git remote set-url origin "https://$1@$ORIGIN"
git remote set-url origin "https://$1@$ORIGIN"
git config --global user.email "$2"
git config --global user.name "$3"

